# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3aa67d4afecbd2b568edce6bde0bdb9def7692ede5ee3b62f2b2ec254fa00b5624356e07ccdef91a63c5fe6004de21b6c9e7840a6fc50b93e4d4776ee3ef37d9

test:
  secret_key_base: beefc706610742d4471f04e8f64afb2cf8a385102293b2652a31e554345998386dcb5ab4008d5b2f6592fda64a95b1424073f830c74c957205e852ab90898f6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
